deployment:
  tasks:
    - export APPPATH=/home/suguad/documentos_fiscales_app
    - export PUBLICPATH=/home/suguad/public_html
    - mkdir -p $APPPATH
    - mkdir -p $PUBLICPATH

    # Copias privadas
    - /bin/cp -R app routes resources config database bootstrap storage $APPPATH/
    - /bin/cp -R lang $APPPATH/ 2>/dev/null || true
    - /bin/cp composer.json composer.lock artisan .env.example package.json pnpm-lock.yaml vite.config.ts tsconfig.json eslint.config.js components.json $APPPATH/
    - /bin/cp phpunit.xml README.md $APPPATH/ 2>/dev/null || true

    # Copias públicas
    - /bin/cp public/.htaccess public/robots.txt public/index.php $PUBLICPATH/
    - /bin/cp public/favicon.ico $PUBLICPATH/ 2>/dev/null || true
    - /bin/cp public/favicon.svg $PUBLICPATH/ 2>/dev/null || true
    - /bin/cp -R public/img $PUBLICPATH/ 2>/dev/null || true
    - /bin/cp -R public/build $PUBLICPATH/ 2>/dev/null || true

    # Parchea index.php (rutas absolutas)
    - sed -i 's|__DIR__.*/vendor/autoload.php|/home/suguad/documentos_fiscales_app/vendor/autoload.php|g' $PUBLICPATH/index.php
    - sed -i 's|__DIR__.*/bootstrap/app.php|/home/suguad/documentos_fiscales_app/bootstrap/app.php|g' $PUBLICPATH/index.php

    # Composer + caches
    - cd $APPPATH && curl -sS https://getcomposer.org/installer | /usr/local/bin/ea-php83 -d allow_url_fopen=1 -- --install-dir=. --filename=composer.phar
    - cd $APPPATH && /usr/local/bin/ea-php83 -d allow_url_fopen=1 -d memory_limit=512M composer.phar install --optimize-autoloader --no-dev --no-interaction
    - cd $APPPATH && /usr/local/bin/ea-php83 -d memory_limit=512M composer.phar dump-autoload -o

    # .env y optimización
    - cd $APPPATH && /bin/cp .env.example .env
    - cd $APPPATH && sed -i 's|^APP_KEY=.*$|APP_KEY=base64:K8vX9mR2pL5nQ7wT1uY6iO3aS9dF2gH4jK8lM0nP5qR7t|g' .env
    - cd $APPPATH && sed -i 's|^APP_URL=.*$|APP_URL=https://sug.uad.mx|g' .env
    - cd $APPPATH && /usr/local/bin/ea-php83 -d memory_limit=512M artisan config:cache || true
    - cd $APPPATH && /usr/local/bin/ea-php83 -d memory_limit=512M artisan route:cache || true
    - cd $APPPATH && /usr/local/bin/ea-php83 -d memory_limit=512M artisan view:cache  || true

    # Storage symlink y permisos
    - rm -f $PUBLICPATH/storage
    - ln -s $APPPATH/storage/app/public $PUBLICPATH/storage
    - find $APPPATH/storage -type d -exec chmod 755 {} \;
    - find $APPPATH/storage -type f -exec chmod 644 {} \;
    - find $APPPATH/bootstrap/cache -type d -exec chmod 755 {} \;
    - find $APPPATH/bootstrap/cache -type f -exec chmod 644 {} \;

    # Garantiza PHP 8.3 y reglas en .htaccess
    - grep -q "AddHandler application/x-httpd-ea-php83 .php" $PUBLICPATH/.htaccess || \
      (echo '<IfModule mime_module>' >> $PUBLICPATH/.htaccess && \
       echo '  AddHandler application/x-httpd-ea-php83 .php' >> $PUBLICPATH/.htaccess && \
       echo '</IfModule>' >> $PUBLICPATH/.htaccess)

    - grep -q "DirectoryIndex index.php" $PUBLICPATH/.htaccess || \
      (echo 'DirectoryIndex index.php' >> $PUBLICPATH/.htaccess)
