---
# .cpanel.yml
# Configuración de despliegue para cPanel
# Proyecto: Laravel 12 + React + Inertia.js - Gestion de Documentos Fiscales Salud

deployment:
  tasks:
    # Definir rutas del servidor
    - export APPPATH=/home/suguad/documentos_app
    - export PUBLICPATH=/home/suguad/public_html
    - mkdir -p $APPPATH

    # Limpiar archivos innecesarios del despliegue anterior
    - rm -f $APPPATH/debug_documents.php 2>/dev/null || true
    - rm -f $APPPATH/debug_php.php 2>/dev/null || true
    - rm -f $APPPATH/debug_route.php 2>/dev/null || true
    - rm -f $APPPATH/temp_clean_controller.php 2>/dev/null || true
    - rm -f $APPPATH/temp_method.php 2>/dev/null || true
    - rm -f $APPPATH/deploy-cpanel.bat 2>/dev/null || true
    - rm -f $APPPATH/deploy-manual-build.bat 2>/dev/null || true
    - rm -f $APPPATH/install_telescope.bat 2>/dev/null || true
    - rm -f $APPPATH/php-dev.ini 2>/dev/null || true
    - rm -f $APPPATH/package-lock.json 2>/dev/null || true
    - rm -f $PUBLICPATH/debug_documents.php 2>/dev/null || true
    - rm -f $PUBLICPATH/debug_php.php 2>/dev/null || true
    - rm -f $PUBLICPATH/debug_route.php 2>/dev/null || true
    - rm -f $PUBLICPATH/package-lock.json 2>/dev/null || true

    # Copiar aplicación Laravel al directorio privado
    - /bin/cp -R app $APPPATH/
    - /bin/cp -R routes $APPPATH/
    - /bin/cp -R resources $APPPATH/
    - /bin/cp -R config $APPPATH/
    - /bin/cp -R database $APPPATH/
    - /bin/cp -R bootstrap $APPPATH/
    - /bin/cp -R storage $APPPATH/
    - /bin/cp -R lang $APPPATH/ 2>/dev/null || true
    - /bin/cp composer.json $APPPATH/
    - /bin/cp composer.lock $APPPATH/
    - /bin/cp composer.phar $APPPATH/ 2>/dev/null || true
    - /bin/cp artisan $APPPATH/
    - /bin/cp .env.example $APPPATH/
    - /bin/cp package.json $APPPATH/ 2>/dev/null || true
    - /bin/cp pnpm-lock.yaml $APPPATH/ 2>/dev/null || true
    - /bin/cp vite.config.ts $APPPATH/ 2>/dev/null || true
    - /bin/cp tsconfig.json $APPPATH/ 2>/dev/null || true

    # Copiar archivos públicos al directorio público
    - /bin/cp -R public/* $PUBLICPATH/
    
    # Asegurar que .htaccess esté presente
    - /bin/cp public/.htaccess $PUBLICPATH/.htaccess
    
    # Copiar el index.php correcto para producción (DEBE SER DESPUÉS de copiar public/*)
    - /bin/cp public/index-cpanel.php $PUBLICPATH/index.php

    # Copiar assets compilados también a la aplicación Laravel
    - /bin/cp -R public/build $APPPATH/public/ 2>/dev/null || true

    # Instalar dependencias de Composer
    - export PATH=/opt/cpanel/ea-php83/root/usr/bin:$PATH
    - cd $APPPATH && /opt/cpanel/ea-php83/root/usr/bin/php composer.phar install --no-dev --no-interaction --prefer-dist --optimize-autoloader 2>/dev/null || curl -sS https://getcomposer.org/installer | /opt/cpanel/ea-php83/root/usr/bin/php && /opt/cpanel/ea-php83/root/usr/bin/php composer.phar install --no-dev --no-interaction --prefer-dist --optimize-autoloader

    # Crear enlace simbólico para storage
    - rm -f $PUBLICPATH/storage
    - ln -s $APPPATH/storage/app/public $PUBLICPATH/storage

    # Optimizar Laravel (cachés)
    - cd $APPPATH && /opt/cpanel/ea-php83/root/usr/bin/php artisan config:cache
    - cd $APPPATH && /opt/cpanel/ea-php83/root/usr/bin/php artisan route:cache
    - cd $APPPATH && /opt/cpanel/ea-php83/root/usr/bin/php artisan view:cache
    - cd $APPPATH && /opt/cpanel/ea-php83/root/usr/bin/php artisan optimize

    # Configurar permisos correctos
    - find $APPPATH/storage -type d -exec chmod 755 {} \;
    - find $APPPATH/storage -type f -exec chmod 644 {} \;
    - find $APPPATH/bootstrap/cache -type d -exec chmod 755 {} \;
    - find $APPPATH/bootstrap/cache -type f -exec chmod 644 {} \;
